[browser]
gatherUsageStats = true
[server]
address = "0.0.0.0"
port = 8501
enableCORS = false
enableXsrfProtection = false
[theme]
primaryColor = "#543FDD"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#FAFAFA"
textColor = "#2E2E38"
